ALL_DATA_TYPES = {
    "Height": "The measurement from the base to the top of a person's body.",
    "BodyMass": "The total weight of an individual.",
    "HeartRate": "The number of heartbeats per minute.",
    "OxygenSaturation": "The percentage of oxygen-saturated hemoglobin in the blood.",
    "RespiratoryRate": "The number of breaths taken per minute.",
    "StepCount": "The number of steps taken by an individual.",
    "DistanceWalkingRunning": "The distance covered while walking or running.",
    "BasalEnergyBurned": "The amount of energy expended by the body at rest to maintain vital functions.",
    "ActiveEnergyBurned": "Calories expended through physical activity.",
    "FlightsClimbed": "The number of flights of stairs ascended.",
    "AppleExerciseTime": "The duration of physical exercise as recorded by Apple devices.",
    "DistanceCycling": "The distance covered while cycling.",
    "DistanceSwimming": "The distance covered while swimming.",
    "RestingHeartRate": "The number of heartbeats per minute while at rest.",
    "VO2Max": "The maximum amount of oxygen the body can utilize during intense exercise, indicating cardiovascular fitness.",
    "WalkingHeartRateAverage": "The average heart rate measured during walking activities.",
    "EnvironmentalAudioExposure": "Measures ambient sound levels to monitor exposure.",
    "HeadphoneAudioExposure": "Tracks audio levels from headphones to prevent hearing damage.",
    "WalkingDoubleSupportPercentage": "The portion of a walking cycle where both feet are on the ground.",
    "SixMinuteWalkTestDistance": "Distance covered in a six-minute walk test.",
    "AppleStandTime": "The amount of time spent standing as recorded by Apple devices.",
    "WalkingSpeed": "The rate at which an individual walks.",
    "WalkingStepLength": "The distance covered in a single step while walking.",
    "WalkingAsymmetryPercentage": "The percentage of time one foot is ahead of the other while walking.",
    "StairAscentSpeed": "The speed of ascending stairs.",
    "StairDescentSpeed": "The speed of descending stairs.",
    "SleepDurationGoal": "The target duration of sleep set by the user.",
    "AppleWalkingSteadiness": "An assessment of gait stability during walking.",
    "HeartRateRecoveryOneMinute": "The reduction in heart rate one minute after peak exercise, indicating cardiovascular fitness.",
    "RunningPower": "The amount of power generated during running activities.",
    "RunningSpeed": "The rate at which an individual runs.",
    "AppleSleepingBreathingDisturbances": "Occurrences of irregular breathing patterns during sleep.",
    "TimeInDaylight": "The amount of time spent exposed to natural daylight.",
    "PhysicalEffort": "The perceived exertion level during physical activities.",
    "HeartRateVariabilitySDNN": "The standard deviation of heartbeat intervals, reflecting autonomic nervous system activity."
}
